
version: '3.3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/data/portainer:/data

  openldap:
    container_name: openldap
    image: docker.io/bitnami/openldap:2.5
    ports:
      - '389:389'
      # - '636:1636'  
    volumes:
      - './docker/data/openldap:/bitnami/openldap'
    environment: 
      - LDAP_ROOT=DC=example,DC=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks: 
      - lab-net

  ldap-backend:
    depends_on: 
      - openldap
    container_name: ldap-backend
    build:
      context: .
      dockerfile: ./ldap-backend.Dockerfile
    command: npm start
    ports: 
      - "1111:1111"
    volumes:
      - ./:/usr/app
    networks: 
      - lab-net

networks: 
  lab-net:
      driver: bridge
